### ISSUE TITLE
LSP crashes when starting

### ISSUE THREAD

**Issue by jackalcooper** [lexical-lsp/vscode-lexical#24]
```
Starting lexical release in "/Users/tsai/Library/Application Support/Code/User/globalStorage/lexical-lsp.lexical/lexical_install/lexical"
init terminating in do_boot ({load_failed,[logger_filters,supervisor,lists,heart,gen,proc_lib,gen_server,logger_server,logger_backend,kernel,logger,error_logger,erl_parse,gen_event,ets,code,erl_lint,erl_eval,file_io_server,code_server,logger_config,application_controller,error_handler,filename,file_server,file,application_master,logger_simple_h,application]})

Crash dump is being written to: erl_crash.dump...done
[Error - 10:53:45 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:53:45 AM] Connection to server got closed. Server will restart.
true
[Error - 10:53:45 AM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
init terminating in do_boot ({load_failed,[erl_parse,application_controller,supervisor,proc_lib,lists,logger_config,logger_simple_h,logger_server,logger_backend,logger_filters,application,gen_server,heart,kernel,logger,gen_event,filename,gen,file_io_server,error_logger,file_server,erl_lint,file,ets,erl_eval,code_server,code,application_master,error_handler]})

Crash dump is being written to: erl_crash.dump...done
[Error - 10:53:46 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:53:46 AM] Connection to server got closed. Server will restart.
true
[Error - 10:53:46 AM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
init terminating in do_boot ({load_failed,[proc_lib,logger_backend,logger_simple_h,logger_server,error_logger,code_server,supervisor,lists,logger_config,logger_filters,kernel,gen,heart,gen_server,gen_event,file_io_server,file_server,filename,file,ets,erl_parse,application_controller,error_handler,erl_lint,erl_eval,code,application_master,application,logger]})

Crash dump is being written to: erl_crash.dump...done
[Error - 10:53:46 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:53:46 AM] Connection to server got closed. Server will restart.
true
[Error - 10:53:46 AM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:53:46 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
init terminating in do_boot ({load_failed,[lists,heart,logger_filters,file_io_server,logger_config,logger_simple_h,logger_server,logger_backend,logger,kernel,gen_server,gen_event,gen,supervisor,proc_lib,filename,file_server,file,ets,error_logger,erl_parse,erl_lint,erl_eval,code_server,code,application_master,application_controller,application,error_handler]})

Crash dump is being written to: erl_crash.dump...done
[Error - 10:53:46 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:53:46 AM] Connection to server got closed. Server will restart.
true
[Error - 10:53:46 AM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:53:46 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
init terminating in do_boot ({load_failed,[logger_backend,logger,logger_simple_h,supervisor,logger_server,gen,file_server,logger_filters,heart,gen_server,code,application_master,kernel,filename,file,gen_event,file_io_server,proc_lib,lists,logger_config,application_controller,error_handler,error_logger,ets,application,erl_parse,erl_eval,erl_lint,code_server]})

Crash dump is being written to: erl_crash.dump...done
[Error - 10:53:46 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:53:46 AM] The Lexical server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:53:46 AM] Lexical client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:53:46 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

```

**Comment by scottming** [comment]
I guess that your project's Erlang version is not 25.2.x

**Comment by Blond11516** [comment]
Hi @jackalcooper. I assume you're getting this error when using the lexical server that gets automatically installed by the extension?

If so, could you follow [the instructions from lexical's repo](https://github.com/lexical-lsp/lexical#installation) to install and build your own version, and then use the `lexical.server.releasePathOverride` to use that release in vscode?

**Comment by Blond11516** [comment]
@jdewar Thanks for the report! Including erts in the release isn't really an option, because that would mean we'd have to build a different release for every architecture we want to support. Doable, but pretty impractical.

@scottming I think there were internal discussions recently about version inconsistencies and `include_erts`. Do you have any more insight on this?

**Comment by Blond11516** [comment]
@scottming Just saw [your comment on the publishing MR](https://www.youtube.com/watch?v=C4cNnVK412U), forget my last comment here.

@jackalcooper @jdewar There is currently an issue with Lexical failing to start when not using Erlang 25.2. The current fix is indeed to change `include_erts` to true and use a local release if you're not able to use Erlang 25.2.

I'll add a mention about this in said MR.

**Comment by scottming** [comment]
@Blond11516 

I think this can be pointed out in the "Troubleshooting" section of the README, so that users have a temporary solution because many users use different versions of Erlang in different projects.

but we need to address this issue in `lexical-lsp/lexical` in the near future.

**Comment by rossvz** [comment]
I'm getting the same error, but I am using `25.2` for OTP version (through asdf)

```
❯ asdf current
elixir          1.13.4-otp-25  
erlang          25.2            
```

And running `code .` from that same shell immediately sees lexical crash:

```
init terminating in do_boot ({load_failed,[logger_simple_h,logger_config,lists,logger,gen_server,kernel,logger_server,logger_filters,code_server,file,gen_event,heart,file_server,error_logger,filename,gen,application,erl_eval,supervisor,erl_lint,file_io_server,code,error_handler,ets,erl_parse,application_master,application_controller,logger_backend,proc_lib]})

Crash dump is being written to: erl_crash.dump...done
[Error - 5:04:54 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 5:04:54 PM] Connection to server got closed. Server will restart.
true
```

**Comment by scohen** [comment]
@rossvz Lexical doesn't work with elixir 1.13, it requires >= 1.14 to work. 

Your last config with 1.15.4 and erl 25 should work though. Did you recompile with those versions?
(the error you're getting is erlang's way of saying there's a version mismatch in the .beam files)

**Comment by abarr** [comment]
Same error for me. I am using:
❯ asdf current 
elixir          1.14.2          
erlang          25.2.1          


I recompiled and restarted vscode but server still fails to start. Let me know if you need anything else to help with problem.

**Comment by scohen** [comment]
For asdf, there are two things to understand.
1. What's the global version of elixir installed? This is the one that your editor sees, and may be managed by asdf
2. What's the project-specific version of elixir installed? This is the one managed by asdf in `.tools-versions`

Presently, Lexical needs to be compiled on a version that's the lowest version between your project versions and the global version. The error you both are getting indicates a version mismatch between where lexical is getting started and your projects (and yes, the erlang `load failed` error is so unhelpful). These errors happen when the compilation version is later than the version specified locally, since the `.beam` files are newer than the VM they're running on. Newer VMs can run on older `.beam` files though. We want to get things in that state. 

This is a bit odd, since the code that ships with the vscode plugin is compiled with erlang 24 and elixir 1.13.

You're not running windows by any chance, are you?

**Comment by scohen** [comment]
also, compiling from source and setting `include_erts` in the release step in `mix.exs` to true _should_ fix these problems.

**Comment by thoughtarray** [comment]
I've a similar issue.
```shell
> asdf current
elixir          1.15.4-otp-25   /home/kgil/.tool-versions
erlang          25.3.2.5        /home/kgil/.tool-versions
```

```txt
init terminating in do_boot ({load_failed, [logger_server,logger_backend,logger_filters,logger,heart,gen_server,gen_event,gen,file_io_server,file_server,filename,file,ets,error_logger,erl_parse,erl_lint,code_server,erl_eval,application_master,code,supervisor,proc_lib,lists,application_controller,error_handler,application,logger_simple_h,logger_config,kernel]})
System version: Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]
```

I'm running on Ubuntu 22.04. VSCode is installed via Ubuntu Software.

Any ideas other than compiling from source?

**Comment by Blond11516** [comment]
Currently, auto-installed versions require you to use the same erlang version as they were built with. As of writing, this is version `24.3.4.13` but should change to `24.3.4.12` in the next release (the change is due to a mishap on our part, sorry about that).

If you wish to use any other version, you have to compile yourself and point the extension to your own build. Compiling yourself isn't hard; all you have to do is clone the repo, `mix deps.get` and `mix release lexical`.

That said, we know this is far from ideal and are working on finding a way to remove this limitation.

Finally, even when building yourself you are limited to using the same erlang version you built Lexical with by default. Changing `include_erts` to `true` lets you use any version you want in your projects.

I realise the README currently isn't super clear about all of this. I'll try to clarify things and update it shortly.

**Comment by thoughtarray** [comment]
Okay, gotcha. That clears it up! Thanks for looking into the README :+1:

**Comment by scohen** [comment]
@thoughtarray @jackalcooper @jdewar @rossvz @abarr @niklas-heer  (whew, I wish there was an `@everyone`)
Just wanted to point out that I have a potential fix for this issue over here: https://github.com/lexical-lsp/lexical/pull/314

**Comment by Blond11516** [comment]
I'm going to close this issue as https://github.com/lexical-lsp/lexical/pull/314 has been merged and released for a while and I haven't heard about anyone having this issue recently. Anyone who is still encountering this is welcome to reopen!
