### ISSUE TITLE
Publish to Open VSX Registry

### ISSUE THREAD

**Issue by adamcstephens** [lexical-lsp/vscode-lexical#49]
Please publish releases to https://open-vsx.org/

Doing so allows open source builds of VS Code to access the extension through a registry.

Thanks!

**Comment by Blond11516** [comment]
Hello again @adamcstephens!

Lexical has been published on Open VSX. You can see the extension here: https://open-vsx.org/extension/lexical-lsp/lexical

I've tested the extension with VSCodium and it appears to work fine.

**Comment by adamcstephens** [comment]
Thank you!
