### ISSUE TITLE
Restart task doesn't work when Lexical failed to start

### ISSUE THREAD

**Issue by bbhoss** [lexical-lsp/vscode-lexical#62]
Install an incompatible version of erlang, try to open your project, then try the restart LS task. it should show this error. The reason I found this is because I updated the version so wanted to get Lexical to recognize it without restarting VSCode. It seems like when it breaks due to version error it can't find this task. From Discord user blond11516:
> Blond: That's a vscode extension issue. The task isn't registered when lexical fails to start because it doesn't re-evaluate the start script path; it only tells vscode to restart the path it already has. I thought vscode wouldn't expose the task if it isn't registered but apparently that was a bad assumption 

![image](https://github.com/lexical-lsp/vscode-lexical/assets/7044/b0fdd398-abad-42f7-a894-88789f74d01a)

**Comment by Blond11516** [comment]
Hi @bbhoss! Sorry for the long delay, I've been busy all week. I was wondering if you had any othe errors when trying to open your project with an incompatible Erlang?

For example, I get these errors when I do. They get dismissed automatically though, so it's easy to miss them if you look away after opening a project:
![image](https://github.com/lexical-lsp/vscode-lexical/assets/44734484/9deb679c-4889-45cd-990c-2be531d5b236)

Also, just to make sure I understand the reproduction steps correctly, you did something along those lines:
1. Have the project configured to use incompatible Erlang version A (through asdf, global install or whatever)
2. Open the project in VSCode
3. Notice incompatible Erlang version
4. Update Erlang version to compatible version B
5. Try to restart Lexical through the command
All without updating Lexical itself?

**Comment by Blond11516** [comment]
I've opened #63, which fixes the issue (assuming I understood it correctly). I'd appreciate it if you could take some time to try it out and see if it works as you expected @bbhoss. Thanks!
