### ISSUE TITLE
Troubles getting syntax highlighting in `heex` files

### ISSUE THREAD

**Issue by mindreframer** [lexical-lsp/vscode-lexical#64]
I can not get syntax highlighting to work in VSCode with Lexical. 

Is it not yet supported or am I missing some additional configuration for this? 

BTW: 
loving Lexical, had only minor issues so far!

**Comment by Blond11516** [comment]
Hi @mindreframer! Syntax highlighting should work as soon as you install the lexical-vscode extension and open an Elixir file (with a `.ex`, `.exs` or `.eex` extension).

Do you get any syntax highlighting at all in elixir files or is everything the default color? Do you have other extensions that might be conflicting with vscode-lexical?

**Comment by mindreframer** [comment]
@Blond11516 Thanks for the response! 

I did figure it out yesterday! Syntax highlighting for Ex(s) files was working, but not for `html.heex` and also not in `~H""" """"` blocks. I remember that ElixirLS had it directly in the extension, but it was taken out. Apparently the `Phonenix` (phoenixframework.phoenix) extension is now responsible for this, and it works now with Lexical and with ElixirLS. I was surprised, that this is not documented anywhere.

Please add this to the docs, so that other users avoid this confusion.

**Comment by Blond11516** [comment]
Glad to hear you figured it out!

I agree it can non-intuitive to have to install a separate extension for HEEX highlighting. I'll keep this issue open as a reminder to add something to the readme.
