### ISSUE TITLE
`do/end` matching bug when `end` is a field of a map/struct

### ISSUE THREAD

**Issue by zachallaun** [lexical-lsp/vscode-lexical#85]
![image](https://github.com/user-attachments/assets/48a3c057-d2a7-42cd-8629-a02fce933591)

The problem here is that the `end` in `current.range.end` matches the `fn`, which causes everything else to be unbalanced. We'll need to add `end` used in this case to the list of allowed unmatched brackets or whatever it is.

**Comment by zachallaun** [comment]
We may be able to just add something like this and then add the name to `unbalancedBracketScopes`:

```json
    {
      "match": "\\.end",
      "name": "SOMETHING"
    },
```

**Comment by ollien** [comment]
What timing. I just hit this at work today!
